### ISSUE TITLE
Tracking bug for unpicking node specific APIs

### ISSUE THREAD

**Issue by PaulKinlan** [polymath-ai/polymath-ai#74]
If we can unpick all the areas that require specific Node APIs then we will be able to run polymath in a number of places such as the Web, Chrome Extensions, Vercel Edge functions, Deno (less of an issue with their npm support).

List of known issues:

* [ ] Axios doesn't work in the browser, need to import `fetch`. Open AI can support setting the adapter, but polymath doesn't pass that option in. Fix this [here](https://github.com/polymath-ai/polymath-ai/blob/0a121c958c420ad1362913d86595630f89cbc87a/core/client/src/main.ts#L63-L64)
  * This might not be an issue now with Dimitri porcelin.
* [ ] Buffer.from used - https://github.com/polymath-ai/polymath-ai/blob/0a121c958c420ad1362913d86595630f89cbc87a/core/host/src/utils.ts#L37-L38 ([PR](https://github.com/polymath-ai/polymath-ai/pull/78))
* [ ] htmlparser2 relies a lot on Buffer and other node libraries
* [x] gpt-3-encoder/Encoder.js requires `fs` -> use https://github.com/niieani/gpt-tokenizer instead...
* [ ] TBD
